openapi: 3.0.1
info:
  title: Task Manager API
  description: API for managing tasks
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api/tasks
    description: Development server
paths:
  /:
    get:
      summary: Get all tasks
      operationId: getAllTasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        description: Task data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created
  /{id}:
    get:
      summary: Get a task by ID
      operationId: getTaskById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of a task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Update a task
      operationId: updateTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
    delete:
      summary: Delete a task
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted
components:
  schemas:
    Task:
      type: object
      required:
        - description
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        description:
          type: string
        creationDate:
          type: string
          format: date-time
        active:
          type: boolean
